[package]
name = "gps-sppofer-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.18.2", features = ["full"] }
redis = "0.21.5"
geo = "0.20.1"
kml = "0.4.3"
either = "1.6.1"
regex = "1.5.5"
